// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705114934_DegreeProgramUpdate")]
    partial class DegreeProgramUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("unitrade")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Identity.Models.AdminProfile", b =>
                {
                    b.Property<Guid>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<int>("UniversityId")
                        .HasColumnType("integer")
                        .HasColumnName("university_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("AdminId")
                        .HasName("pk_admin_profiles");

                    b.HasIndex("UniversityId")
                        .HasDatabaseName("ix_admin_profiles_university_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_profiles_user_id");

                    b.ToTable("admin_profiles", "unitrade");
                });

            modelBuilder.Entity("Modules.Identity.Models.StudentProfile", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<string>("DegreeProgram")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("degree_program");

                    b.Property<decimal>("ReputationScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("reputation_score");

                    b.Property<string>("StudentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("student_number");

                    b.Property<int>("UniversityId")
                        .HasColumnType("integer")
                        .HasColumnName("university_id");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("verification_status");

                    b.Property<int>("YearOfStudy")
                        .HasColumnType("integer")
                        .HasColumnName("year_of_study");

                    b.HasKey("StudentId")
                        .HasName("pk_student_profiles");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_student_course");

                    b.HasIndex("UniversityId")
                        .HasDatabaseName("ix_student_university");

                    b.HasIndex("VerificationStatus")
                        .HasDatabaseName("ix_student_status");

                    b.ToTable("student_profiles", "unitrade", t =>
                        {
                            t.HasCheckConstraint("chk_student_verification", "verification_status IN ('pending', 'partial', 'verified', 'rejected')");

                            t.HasCheckConstraint("chk_student_year", "year_of_study BETWEEN 1 AND 8");
                        });
                });

            modelBuilder.Entity("Modules.Identity.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", "unitrade", t =>
                        {
                            t.HasTrigger("tr_users_updated_at");

                            t.HasCheckConstraint("chk_user_role", "role IN ('student', 'admin')");
                        });
                });

            modelBuilder.Entity("Modules.Identity.Models.VerificationRequest", b =>
                {
                    b.Property<Guid>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("verification_id");

                    b.Property<string>("AdminDecision")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("admin_decision");

                    b.Property<Guid?>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<decimal?>("AiConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ai_confidence_score");

                    b.Property<string>("AiDecision")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ai_decision");

                    b.Property<int>("AttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_number");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("OtpCodeHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("otp_code_hash");

                    b.Property<DateTime>("OtpExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_expires_at");

                    b.Property<int?>("OtpResendCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("otp_resend_count");

                    b.Property<DateTime?>("OtpSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_sent_at");

                    b.Property<DateTime?>("OtpVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_verified_at");

                    b.Property<string>("PorFilePath")
                        .HasColumnType("text")
                        .HasColumnName("por_file_path");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("otp_pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int?>("TotalAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_attempt_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("VerificationId")
                        .HasName("pk_verification_requests");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_vr_status");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uix_vr_current")
                        .HasFilter("is_current = true");

                    b.ToTable("verification_requests", "unitrade", t =>
                        {
                            t.HasTrigger("tr_verification_set_current");

                            t.HasCheckConstraint("chk_vr_status", "status IN ('otp_pending', 'por_pending','under_review','approved', 'rejected')");
                        });
                });

            modelBuilder.Entity("Modules.Listings.Models.BookDetails", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<string>("Author")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("author");

                    b.Property<string>("Edition")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("edition");

                    b.Property<string>("Isbn")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("isbn");

                    b.HasKey("ListingId")
                        .HasName("pk_book_details");

                    b.ToTable("book_details", "unitrade", t =>
                        {
                            t.HasCheckConstraint("chk_isbn_validity", "isbn IS NULL OR length(isbn) IN  (10,13)");
                        });
                });

            modelBuilder.Entity("Modules.Listings.Models.Listing", b =>
                {
                    b.Property<Guid>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiRiskLevel")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ai_risk_level");

                    b.Property<decimal?>("AiRiskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ai_risk_score");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("condition");

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int?>("CourseId1")
                        .HasColumnType("integer")
                        .HasColumnName("course_id1");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("ListingCategoryCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("listing_category_category_id");

                    b.Property<string>("ListingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("listing_status");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.Property<int?>("VisibilityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("visibility_score");

                    b.Property<bool?>("isBundle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_bundle");

                    b.HasKey("ListingId")
                        .HasName("pk_listings");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_listings_category");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_listings_course");

                    b.HasIndex("CourseId1")
                        .HasDatabaseName("ix_listings_course_id1");

                    b.HasIndex("ListingCategoryCategoryId")
                        .HasDatabaseName("ix_listings_listing_category_category_id");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_listings_seller");

                    b.HasIndex("CategoryId", "ListingStatus", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_listings_category_browse")
                        .HasFilter("listing_status = 'live'");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CategoryId", "ListingStatus", "CreatedAt"), new[] { "Title", "Price", "SellerId" });

                    b.HasIndex("CourseId", "ListingStatus", "CreatedAt")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_listings_course_browse")
                        .HasFilter("listing_status = 'live'");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CourseId", "ListingStatus", "CreatedAt"), new[] { "Title", "Price", "SellerId", "CategoryId" });

                    b.HasIndex("ListingStatus", "VisibilityScore", "CreatedAt")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_listings_feed")
                        .HasFilter("listing_status = 'live'");

                    b.ToTable("listings", "unitrade", t =>
                        {
                            t.HasTrigger("tr_listings_updated_at");

                            t.HasCheckConstraint("chk_listing_condition", "condition IN ('new', 'good', 'fair', 'poor')");

                            t.HasCheckConstraint("chk_listing_price", "price > 0");

                            t.HasCheckConstraint("chk_listing_risk", "ai_risk_level IS NULL OR ai_risk_level IN ('low', 'medium', 'high')");

                            t.HasCheckConstraint("chk_listing_status", "listing_status IN ('draft', 'pending', 'live', 'low_visibility', 'rejected', 'sold', 'removed')");
                        });
                });

            modelBuilder.Entity("Modules.Listings.Models.ListingCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId")
                        .HasName("pk_listing_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_listing_categories_name");

                    b.ToTable("listing_categories", "unitrade");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            IsActive = true,
                            Name = "book"
                        },
                        new
                        {
                            CategoryId = 2,
                            IsActive = true,
                            Name = "electronics"
                        },
                        new
                        {
                            CategoryId = 3,
                            IsActive = true,
                            Name = "stationery"
                        },
                        new
                        {
                            CategoryId = 4,
                            IsActive = true,
                            Name = "furniture"
                        },
                        new
                        {
                            CategoryId = 5,
                            IsActive = true,
                            Name = "clothing"
                        },
                        new
                        {
                            CategoryId = 6,
                            IsActive = true,
                            Name = "other"
                        });
                });

            modelBuilder.Entity("Modules.Listings.Models.ListingImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("image_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<int>("FileSize")
                        .HasColumnType("integer")
                        .HasColumnName("file_size");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("image_data");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ImageId")
                        .HasName("pk_listing_images");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_listing_images_listing");

                    b.ToTable("listing_images", "unitrade");
                });

            modelBuilder.Entity("Modules.ReferenceData.Course.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_code");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_name");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("faculty");

                    b.Property<int>("UniversityId")
                        .HasColumnType("integer")
                        .HasColumnName("university_id");

                    b.HasKey("CourseId")
                        .HasName("pk_courses");

                    b.HasIndex("CourseCode")
                        .IsUnique()
                        .HasDatabaseName("ix_courses_course_code");

                    b.HasIndex("UniversityId")
                        .HasDatabaseName("ix_courses_university_id");

                    b.ToTable("courses", "unitrade");
                });

            modelBuilder.Entity("Modules.ReferenceData.University.University", b =>
                {
                    b.Property<int>("UniversityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("university_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UniversityId"));

                    b.Property<string>("EmailDomain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_domain");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("UniversityId")
                        .HasName("pk_universities");

                    b.HasIndex("EmailDomain")
                        .IsUnique()
                        .HasDatabaseName("ix_universities_email_domain");

                    b.ToTable("universities", "unitrade");
                });

            modelBuilder.Entity("Modules.Identity.Models.AdminProfile", b =>
                {
                    b.HasOne("Modules.ReferenceData.University.University", null)
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_profiles_universities_university_id");

                    b.HasOne("Modules.Identity.Models.User", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("Modules.Identity.Models.AdminProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Modules.Identity.Models.StudentProfile", b =>
                {
                    b.HasOne("Modules.ReferenceData.Course.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_student_profiles_courses_course_id");

                    b.HasOne("Modules.Identity.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("Modules.Identity.Models.StudentProfile", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_profiles_users_student_id");

                    b.HasOne("Modules.ReferenceData.University.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_profiles_universities_university_id");

                    b.Navigation("University");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Modules.Identity.Models.VerificationRequest", b =>
                {
                    b.HasOne("Modules.Identity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verification_requests_users_user_id");
                });

            modelBuilder.Entity("Modules.Listings.Models.BookDetails", b =>
                {
                    b.HasOne("Modules.Listings.Models.Listing", "Listing")
                        .WithOne("BookDetails")
                        .HasForeignKey("Modules.Listings.Models.BookDetails", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_details_listings_listing_id");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Modules.Listings.Models.Listing", b =>
                {
                    b.HasOne("Modules.Listings.Models.ListingCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_listings_listing_categories_category_id");

                    b.HasOne("Modules.ReferenceData.Course.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_listings_courses_course_id");

                    b.HasOne("Modules.ReferenceData.Course.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId1")
                        .HasConstraintName("fk_listings_courses_course_id1");

                    b.HasOne("Modules.Listings.Models.ListingCategory", null)
                        .WithMany("Listings")
                        .HasForeignKey("ListingCategoryCategoryId")
                        .HasConstraintName("fk_listings_listing_categories_listing_category_category_id");

                    b.HasOne("Modules.Identity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_listings_users_seller_id");

                    b.Navigation("Category");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Modules.Listings.Models.ListingImage", b =>
                {
                    b.HasOne("Modules.Listings.Models.Listing", "Listing")
                        .WithMany("Images")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listing_images_listings_listing_id");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Modules.ReferenceData.Course.Course", b =>
                {
                    b.HasOne("Modules.ReferenceData.University.University", null)
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_courses_universities_university_id");
                });

            modelBuilder.Entity("Modules.Identity.Models.User", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Modules.Listings.Models.Listing", b =>
                {
                    b.Navigation("BookDetails");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Modules.Listings.Models.ListingCategory", b =>
                {
                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
