using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class SeedCourses : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "faculty",
                schema: "unitrade",
                table: "courses",
                type: "text",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true
            );

            migrationBuilder.Sql(
                @"INSERT INTO unitrade.courses (university_id, course_code, course_name, faculty)
                    VALUES
                        (2, 'IMY 210', 'Advanced web technologies 1 210', 'EBIT'),
                        (2, 'IMY 220', 'Advanced web technologies 2 220', 'EBIT'),
                        (2, 'MLV 420', 'Aeronautics 420', 'EBIT'),
                        (2, 'AFT 121', 'African languages literature: Capita selecta 121', 'EBIT'),
                        (2, 'AFT 220', 'African languages literature: Capita selecta 220', 'EBIT'),
                        (2, 'AFT 320', 'African languages literature: Capita selecta 320', 'EBIT'),
                        (2, 'AFR 110', 'Afrikaans 110', 'EBIT'),
                        (2, 'AFR 120', 'Afrikaans 120', 'EBIT'),
                        (2, 'AFR 214', 'Afrikaans 214', 'EBIT'),
                        (2, 'AFR 220', 'Afrikaans 220', 'EBIT'),
                        (2, 'AFR 311', 'Afrikaans 311', 'EBIT'),
                        (2, 'AFR 321', 'Afrikaans 321', 'EBIT'),
                        (2, 'ENE 310', 'Analogue electronics 310', 'EBIT'),
                        (2, 'WST 212', 'Applications in data science 212', 'EBIT'),
                        (2, 'AGL 110', 'Archaeology 110', 'EBIT'),
                        (2, 'AGL 120', 'Archaeology 120', 'EBIT'),
                        (2, 'COS 314', 'Artificial intelligence 314', 'EBIT'),
                        (2, 'GGY 156', 'Aspects of human geography 156', 'EBIT'),
                        (2, 'EBT 410', 'Automation 410', 'EBIT'),
                        (2, 'MBY 251', 'Bacteriology 251', 'EBIT'),
                        (2, 'AIM 111', 'Academic information management 111', 'EBIT'),
                        (2, 'AIM 121', 'Academic information management 121', 'EBIT'),
                        (2, 'ALL 122', 'Academic literacy for Construction Economics 122', 'EBIT'),
                        (2, 'ALL 121', 'Academic literacy for Information Technology 121', 'EBIT'),
                        (2, 'ALL 123', 'Academic literacy for Town and Regional Planning 123', 'EBIT'),
                        (2, 'UPO 112', 'Academic orientation 112', 'EBIT'),
                        (2, 'JPO 111', 'Additional chemistry 1 111', 'EBIT'),
                        (2, 'JPO 161', 'Additional chemistry 1 161', 'EBIT'),
                        (2, 'JPO 121', 'Additional chemistry 2 121', 'EBIT'),
                        (2, 'JPO 112', 'Additional electricity and electronics 112', 'EBIT'),
                        (2, 'JPO 113', 'Additional engineering design tools 113', 'EBIT'),
                        (2, 'JPO 123', 'Additional materials science 123', 'EBIT'),
                        (2, 'JPO 116', 'Additional mathematics 1 116', 'EBIT'),
                        (2, 'JPO 126', 'Additional mathematics 2 126', 'EBIT'),
                        (2, 'JPO 122', 'Additional physics 122', 'EBIT'),
                        (2, 'JPO 152', 'Additional physics 152', 'EBIT'),
                        (2, 'JPO 114', 'Additional programming 1 114', 'EBIT'),
                        (2, 'JPO 124', 'Additional programming 2 124', 'EBIT'),
                        (2, 'JPO 125', 'Additional statics 125', 'EBIT'),
                        (2, 'ENE 410', 'Advanced electronics 410', 'EBIT'),
                        (2, 'PEE 321', 'Basic mine ventilation engineering 321', 'EBIT'),
                        (2, 'CBI 310', 'Biochemical engineering 310', 'EBIT'),
                        (2, 'EBI 410', 'Biomedical Engineering 410', 'EBIT'),
                        (2, 'EPR 404', 'Biomedical Engineering Project 404', 'EBIT'),
                        (2, 'BME 120', 'Biometry 120', 'EBIT'),
                        (2, 'BOU 111', 'Building drawings 111', 'EBIT'),
                        (2, 'BGG 121', 'Building organisation 121', 'EBIT'),
                        (2, 'BWT 110', 'Building science 110', 'EBIT'),
                        (2, 'BWT 120', 'Building science 120', 'EBIT'),
                        (2, 'BWT 210', 'Building science 210', 'EBIT'),
                        (2, 'BWT 220', 'Building science 220', 'EBIT'),
                        (2, 'BWT 310', 'Building science 310', 'EBIT'),
                        (2, 'BWT 320', 'Building science 320', 'EBIT'),
                        (2, 'GBD 112', 'Building services 112', 'EBIT'),
                        (2, 'GBD 122', 'Building services 122', 'EBIT'),
                        (2, 'GBD 211', 'Building services 211', 'EBIT'),
                        (2, 'GBD 221', 'Building services 221', 'EBIT'),
                        (2, 'GBD 311', 'Building services 311', 'EBIT'),
                        (2, 'BAC 200', 'Business accounting 200', 'EBIT'),
                        (2, 'BAC 201', 'Business accounting 201', 'EBIT'),
                        (2, 'OBS 370', 'Business analytics 370', 'EBIT'),
                        (2, 'OBS 212', 'Business creation 212', 'EBIT'),
                        (2, 'BPZ 321', 'Business engineering 321', 'EBIT'),
                        (2, 'BER 310', 'Business law 310', 'EBIT'),
                        (2, 'OBS 114', 'Business management 114', 'EBIT'),
                        (2, 'OBS 124', 'Business management 124', 'EBIT'),
                        (2, 'OBS 210', 'Business management 210', 'EBIT'),
                        (2, 'OBS 220', 'Business management 220', 'EBIT'),
                        (2, 'OBS 310', 'Business management 310', 'EBIT'),
                        (2, 'OBS 330', 'Business management 330', 'EBIT'),
                        (2, 'WTW 114', 'Calculus 114', 'EBIT'),
                        (2, 'WTW 148', 'Calculus 148', 'EBIT'),
                        (2, 'WTW 158', 'Calculus 158', 'EBIT'),
                        (2, 'WTW 258', 'Calculus 258', 'EBIT'),
                        (2, 'GMC 110', 'Cartography 110', 'EBIT'),
                        (2, 'CIR 113', 'Chemical engineering 113', 'EBIT'),
                        (2, 'CIR 123', 'Chemical engineering 123', 'EBIT'),
                        (2, 'CIR 211', 'Chemical engineering 211', 'EBIT'),
                        (2, 'CIR 310', 'Chemical engineering 310', 'EBIT'),
                        (2, 'CIO 320', 'Chemical engineering design 320', 'EBIT'),
                        (2, 'CIM 211', 'Chemical engineering materials 211', 'EBIT'),
                        (2, 'CPR 420', 'Chemical engineering practice 420', 'EBIT'),
                        (2, 'CHM 215', 'Chemistry 215', 'EBIT'),
                        (2, 'CHM 226', 'Chemistry 226', 'EBIT'),
                        (2, 'SBM 321', 'Civil building materials 321', 'EBIT'),
                        (2, 'SBZ 420', 'Civil engineering construction management 420', 'EBIT'),
                        (2, 'SIE 310', 'Civil engineering economics 310', 'EBIT'),
                        (2, 'SBZ 321', 'Civil engineering measurement techniques 321', 'EBIT'),
                        (2, 'SKE 220', 'Civil engineering services 220', 'EBIT'),
                        (2, 'SEV 421', 'Civil environmental management 421', 'EBIT'),
                        (2, 'KRG 110', 'Commercial law 110', 'EBIT'),
                        (2, 'KRG 120', 'Commercial law 120', 'EBIT'),
                        (2, 'KOB 281', 'Communication management 281', 'EBIT'),
                        (2, 'JCP 201', 'Community-based project 201', 'EBIT'),
                        (2, 'JCP 202', 'Community-based project 202', 'EBIT'),
                        (2, 'JCP 203', 'Community-based project 203', 'EBIT'),
                        (2, 'COS 341', 'Compiler construction 341', 'EBIT'),
                        (2, 'MKM 411', 'Computational fluid dynamics 411', 'EBIT'),
                        (2, 'SCA 420', 'Computer applications in civil engineering 420', 'EBIT'),
                        (2, 'ERD 320', 'Computer engineering design 320', 'EBIT'),
                        (2, 'EAS 410', 'Computer engineering: Architecture and systems 410', 'EBIT'),
                        (2, 'COS 344', 'Computer graphics 344', 'EBIT'),
                        (2, 'COS 332', 'Computer networks 332', 'EBIT'),
                        (2, 'COS 284', 'Computer organisation and architecture 284', 'EBIT'),
                        (2, 'COS 330', 'Computer security and ethics 330', 'EBIT'),
                        (2, 'COS 226', 'Concurrent systems 226', 'EBIT'),
                        (2, 'KON 111', 'Construction 111', 'EBIT'),
                        (2, 'KON 121', 'Construction 121', 'EBIT'),
                        (2, 'KON 210', 'Construction 210', 'EBIT'),
                        (2, 'KON 220', 'Construction 220', 'EBIT'),
                        (2, 'KON 300', 'Construction 300', 'EBIT'),
                        (2, 'KBS 310', 'Construction management 310', 'EBIT'),
                        (2, 'KBS 320', 'Construction management 320', 'EBIT'),
                        (2, 'KSH 201', 'Construction quantities 201', 'EBIT'),
                        (2, 'KSH 300', 'Construction quantities 300', 'EBIT'),
                        (2, 'BEM 212', 'Consumer behaviour 212', 'EBIT'),
                        (2, 'EBB 320', 'Control systems 320', 'EBIT'),
                        (2, 'NKR 410', 'Corrosion 410', 'EBIT'),
                        (2, 'KRM 110', 'Criminology 110', 'EBIT'),
                        (2, 'KRM 120', 'Criminology 120', 'EBIT'),
                        (2, 'KRM 210', 'Criminology 210', 'EBIT'),
                        (2, 'KRM 220', 'Criminology 220', 'EBIT'),
                        (2, 'COS 212', 'Data structures and algorithms 212', 'EBIT'),
                        (2, 'COS 326', 'Database systems 326', 'EBIT'),
                        (2, 'ONT 100', 'Design 100', 'EBIT'),
                        (2, 'ONT 200', 'Design 200', 'EBIT'),
                        (2, 'ONT 300', 'Design 300', 'EBIT'),
                        (2, 'OKU 100', 'Design communication 100', 'EBIT'),
                        (2, 'OKU 200', 'Design communication 200', 'EBIT'),
                        (2, 'OKU 300', 'Design communication 300', 'EBIT'),
                        (2, 'MOX 410', 'Design project 410', 'EBIT'),
                        (2, 'CPJ 421', 'Design project 421', 'EBIT'),
                        (2, 'OBS 211', 'Design thinking and business innovation 211', 'EBIT'),
                        (2, 'SDO 420', 'Detailed design 420', 'EBIT'),
                        (2, 'WTW 256', 'Differential equations 256', 'EBIT'),
                        (2, 'IMY 120', 'Digital authoring tools 120', 'EBIT'),
                        (2, 'EDC 310', 'Digital communication 310', 'EBIT'),
                        (2, 'BEM 231', 'Digital marketing 231', 'EBIT'),
                        (2, 'ERS 220', 'Digital systems 220', 'EBIT'),
                        (2, 'WTW 115', 'Discrete structures 115', 'EBIT'),
                        (2, 'WTW 285', 'Discrete structures 285', 'EBIT'),
                        (2, 'ESP 300', 'DSP programming 300', 'EBIT'),
                        (2, 'ESP 411', 'DSP programming and application 411', 'EBIT'),
                        (2, 'WTW 162', 'Dynamical processes 162', 'EBIT'),
                        (2, 'MSD 210', 'Dynamics 210', 'EBIT'),
                        (2, 'EHN 410', 'e-Business and network security 410', 'EBIT'),
                        (2, 'GLY 163', 'Earth history 163', 'EBIT'),
                        (2, 'AAL 110', 'Earth studies 110', 'EBIT'),
                        (2, 'AAL 120', 'Earth studies 120', 'EBIT'),
                        (2, 'AAL 210', 'Earth studies 210', 'EBIT'),
                        (2, 'AAL 220', 'Earth studies 220', 'EBIT'),
                        (2, 'AAL 310', 'Earth studies 310', 'EBIT'),
                        (2, 'AAL 320', 'Earth studies 320', 'EBIT'),
                        (2, 'EKN 110', 'Economics 110', 'EBIT'),
                        (2, 'EKN 120', 'Economics 120', 'EBIT'),
                        (2, 'EKN 214', 'Economics 214', 'EBIT'),
                        (2, 'EKN 234', 'Economics 234', 'EBIT'),
                        (2, 'EKN 310', 'Economics 310', 'EBIT'),
                        (2, 'EKN 320', 'Economics 320', 'EBIT'),
                        (2, 'EAD 410', 'Electrical drives 410', 'EBIT'),
                        (2, 'EIR 211', 'Electrical engineering 211', 'EBIT'),
                        (2, 'EIR 221', 'Electrical engineering 221', 'EBIT'),
                        (2, 'EWE 320', 'Electrical engineering design 320', 'EBIT'),
                        (2, 'ELX 311', 'Electrical machines 311', 'EBIT'),
                        (2, 'EBN 111', 'Electricity and electronics 111', 'EBIT'),
                        (2, 'EBN 122', 'Electricity and electronics 122', 'EBIT'),
                        (2, 'EME 310', 'Electromagnetic compatibility 310', 'EBIT'),
                        (2, 'EMZ 310', 'Electromagnetism 310', 'EBIT'),
                        (2, 'ELO 320', 'Electronic engineering design 320', 'EBIT'),
                        (2, 'MIA 320', 'Engineering activity and group work 320', 'EBIT'),
                        (2, 'MGC 110', 'Engineering design tools 110', 'EBIT'),
                        (2, 'BIE 420', 'Engineering economics 420', 'EBIT'),
                        (2, 'BSS 310', 'Engineering management 310', 'EBIT'),
                        (2, 'IPI 410', 'Engineering professionalism 410', 'EBIT'),
                        (2, 'BES 220', 'Engineering statistics 220', 'EBIT'),
                        (2, 'ENG 110', 'English 110', 'EBIT'),
                        (2, 'ENG 120', 'English 120', 'EBIT'),
                        (2, 'ENG 220', 'English 220', 'EBIT'),
                        (2, 'ENG 310', 'English 310', 'EBIT'),
                        (2, 'ENG 320', 'English 320', 'EBIT'),
                        (2, 'ENG 118', 'English for specific purposes 118', 'EBIT'),
                        (2, 'PPY 220', 'Experiential training 220', 'EBIT'),
                        (2, 'PPY 320', 'Experiential training 320', 'EBIT'),
                        (2, 'SCI 154', 'Exploring the universe 154', 'EBIT'),
                        (2, 'FRK 111', 'Financial accounting 111', 'EBIT'),
                        (2, 'FRK 121', 'Financial accounting 121', 'EBIT'),
                        (2, 'FRK 122', 'Financial accounting 122', 'EBIT'),
                        (2, 'FBS 110', 'Financial management 110', 'EBIT'),
                        (2, 'FBS 210', 'Financial management 210', 'EBIT'),
                        (2, 'FBS 361', 'Financial management 361', 'EBIT'),
                        (2, 'PHY 114', 'First course in physics 114', 'EBIT'),
                        (2, 'PHY 124', 'First course in physics 124', 'EBIT'),
                        (2, 'MTV 310', 'Fluid mechanics 310', 'EBIT'),
                        (2, 'FRN 113', 'French: Cultural-professional (1) 113', 'EBIT'),
                        (2, 'FRN 364', 'French: Cultural-professional (10) 364', 'EBIT'),
                        (2, 'FRN 123', 'French: Cultural-professional (2) 123', 'EBIT'),
                        (2, 'FRN 361', 'French: Cultural-professional (7) 361', 'EBIT'),
                        (2, 'FRN 362', 'French: Cultural-professional (8) 362', 'EBIT'),
                        (2, 'FRN 363', 'French: Cultural-professional (9) 363', 'EBIT'),
                        (2, 'FRN 211', 'French: Intermediate (1) 211', 'EBIT'),
                        (2, 'FRN 221', 'French: Intermediate (2) 221', 'EBIT'),
                        (2, 'CMY 117', 'General chemistry 117', 'EBIT'),
                        (2, 'CMY 127', 'General chemistry 127', 'EBIT'),
                        (2, 'CHM 171', 'General chemistry 171', 'EBIT'),
                        (2, 'CHM 172', 'General chemistry 172', 'EBIT'),
                        (2, 'CHM 181', 'General chemistry 181', 'EBIT'),
                        (2, 'GTS 261', 'Genetic diversity and evolution 261', 'EBIT'),
                        (2, 'GTS 354', 'Genome evolution and phylogenetics 354', 'EBIT'),
                        (2, 'GLY 352', 'Geodynamics and ore formation 352', 'EBIT'),
                        (2, 'GIS 220', 'Geographic data analysis 220', 'EBIT'),
                        (2, 'GIS 310', 'Geographic information systems 310', 'EBIT'),
                        (2, 'GLY 256', 'Geology for engineering 256', 'EBIT'),
                        (2, 'SGM 323', 'Geotechnical engineering 323', 'EBIT'),
                        (2, 'DTS 113', 'German: Cultural-professional (1) 113', 'EBIT'),
                        (2, 'DTS 364', 'German: Cultural-professional (10) 364', 'EBIT'),
                        (2, 'DTS 123', 'German: Cultural-professional (2) 123', 'EBIT'),
                        (2, 'DTS 361', 'German: Cultural-professional (7) 361', 'EBIT'),
                        (2, 'DTS 362', 'German: Cultural-professional (8) 362', 'EBIT'),
                        (2, 'DTS 363', 'German: Cultural-professional (9) 363', 'EBIT'),
                        (2, 'DTS 211', 'German: Intermediate (1) 211', 'EBIT'),
                        (2, 'DTS 221', 'German: Intermediate (2) 221', 'EBIT'),
                        (2, 'MHM 420', 'Heat and mass transfer 420', 'EBIT'),
                        (2, 'MTV 410', 'Heat transfer 410', 'EBIT'),
                        (2, 'EFK 120', 'Heritage tourism management 120', 'EBIT'),
                        (2, 'OML 110', 'History of the environment 110', 'EBIT'),
                        (2, 'OML 120', 'History of the environment 120', 'EBIT'),
                        (2, 'OML 210', 'History of the environment 210', 'EBIT'),
                        (2, 'OML 220', 'History of the environment 220', 'EBIT'),
                        (2, 'OMG 310', 'History of the environment 310', 'EBIT'),
                        (2, 'OMG 320', 'History of the environment 320', 'EBIT'),
                        (2, 'BHU 320', 'Housing 320', 'EBIT'),
                        (2, 'IMY 310', 'Human-computer interaction 310', 'EBIT'),
                        (2, 'SHC 220', 'Hydraulics 220', 'EBIT'),
                        (2, 'SHC 310', 'Hydraulics 310', 'EBIT'),
                        (2, 'SHC 321', 'Hydraulics 321', 'EBIT'),
                        (2, 'SHC 410', 'Hydraulics 410', 'EBIT'),
                        (2, 'NHM 322', 'Hydrometallurgy 322', 'EBIT'),
                        (2, 'NHM 412', 'Hydrometallurgy 412', 'EBIT'),
                        (2, 'COS 132', 'Imperative programming 132', 'EBIT'),
                        (2, 'BAN 313', 'Industrial analysis 313', 'EBIT'),
                        (2, 'PNB 300', 'Industrial excursions 300', 'EBIT'),
                        (2, 'NPY 316', 'Industrial training 316', 'EBIT'),
                        (2, 'NPY 416', 'Industrial training 416', 'EBIT'),
                        (2, 'INF 112', 'Informatics 112', 'EBIT'),
                        (2, 'INF 154', 'Informatics 154', 'EBIT'),
                        (2, 'INF 164', 'Informatics 164', 'EBIT'),
                        (2, 'INF 171', 'Informatics 171', 'EBIT'),
                        (2, 'INF 183', 'Informatics 183', 'EBIT'),
                        (2, 'INF 214', 'Informatics 214', 'EBIT'),
                        (2, 'INF 225', 'Informatics 225', 'EBIT'),
                        (2, 'INF 261', 'Informatics 261', 'EBIT'),
                        (2, 'INF 271', 'Informatics 271', 'EBIT'),
                        (2, 'INF 272', 'Informatics 272', 'EBIT'),
                        (2, 'INF 315', 'Informatics 315', 'EBIT'),
                        (2, 'INF 324', 'Informatics 324', 'EBIT'),
                        (2, 'INF 354', 'Informatics 354', 'EBIT'),
                        (2, 'INF 370', 'Informatics 370', 'EBIT'),
                        (2, 'KUB 420', 'Information and communications technology law 420', 'EBIT'),
                        (2, 'INL 110', 'Information science 110', 'EBIT'),
                        (2, 'INL 120', 'Information science 120', 'EBIT'),
                        (2, 'INL 130', 'Information science 130', 'EBIT'),
                        (2, 'INL 140', 'Information science 140', 'EBIT'),
                        (2, 'INL 210', 'Information science 210', 'EBIT'),
                        (2, 'INL 220', 'Information science 220', 'EBIT'),
                        (2, 'INL 230', 'Information science 230', 'EBIT'),
                        (2, 'INL 240', 'Information science 240', 'EBIT'),
                        (2, 'INL 260', 'Information science 260', 'EBIT'),
                        (2, 'INL 270', 'Information science 270', 'EBIT'),
                        (2, 'INL 310', 'Information science 310', 'EBIT'),
                        (2, 'INL 320', 'Information science 320', 'EBIT'),
                        (2, 'INL 340', 'Information science 340', 'EBIT'),
                        (2, 'INL 360', 'Information science 360', 'EBIT'),
                        (2, 'INL 380', 'Information science 380', 'EBIT'),
                        (2, 'INL 370', 'Information science: Work integrated learning and experience 370', 'EBIT'),
                        (2, 'INF 113', 'Information systems 113', 'EBIT'),
                        (2, 'BID 320', 'Information systems design 320', 'EBIT'),
                        (2, 'EIW 121', 'Information technology practice 121', 'EBIT'),
                        (2, 'EIW 221', 'Information technology practice 221', 'EBIT'),
                        (2, 'EIW 320', 'Information technology practice 320', 'EBIT'),
                        (2, 'SVC 412', 'Infrastructure planning 412', 'EBIT'),
                        (2, 'TPW 310', 'Institutional and legal structures for planning 310', 'EBIT'),
                        (2, 'EAI 320', 'Intelligent systems 320', 'EBIT'),
                        (2, 'ISB 201', 'Interaction Design 201', 'EBIT'),
                        (2, 'IMY 211', 'Interactive technology theory 211', 'EBIT'),
                        (2, 'IAU 200', 'Internal auditing 200', 'EBIT'),
                        (2, 'IAU 300', 'Internal auditing 300', 'EBIT'),
                        (2, 'OBS 359', 'International business management 359', 'EBIT'),
                        (2, 'COS 151', 'Introduction to computer science 151', 'EBIT'),
                        (2, 'KKR 322', 'Introduction to construction contract law 322', 'EBIT'),
                        (2, 'COS 221', 'Introduction to database systems 221', 'EBIT'),
                        (2, 'TPD 210', 'Introduction to development planning 210', 'EBIT'),
                        (2, 'ENV 101', 'Introduction to environmental sciences 101', 'EBIT'),
                        (2, 'GLY 155', 'Introduction to geology 155', 'EBIT'),
                        (2, 'ISB 101', 'Introduction to interaction design 101', 'EBIT'),
                        (2, 'NDE 110', 'Introduction to isiNdebele Grammar – Capita selecta 110', 'EBIT'),
                        (2, 'ZUL 111', 'Introduction to isiZulu grammar – Capita selecta 111', 'EBIT'),
                        (2, 'MBY 161', 'Introduction to microbiology 161', 'EBIT'),
                        (2, 'PMY 121', 'Introduction to mining 121', 'EBIT'),
                        (2, 'FIL 251', 'Introduction to moral and political philosophy 251', 'EBIT'),
                        (2, 'GGY 168', 'Introduction to physical geography 168', 'EBIT'),
                        (2, 'TRP 110', 'Introduction to planning 110', 'EBIT'),
                        (2, 'EMR 201', 'Introduction to programming and computer simulations 201', 'EBIT'),
                        (2, 'PSC 321', 'Introduction to project 321', 'EBIT'),
                        (2, 'SEP 111', 'Introduction to Sepedi grammar - Capita selecta 111', 'EBIT'),
                        (2, 'SKE 110', 'Introduction to structures 110', 'EBIT'),
                        (2, 'JSU 110', 'Introduction to sustainable engineering I 110', 'EBIT'),
                        (2, 'JSU 120', 'Introduction to sustainable engineering II 120', 'EBIT'),
                        (2, 'EFK 110', 'Introduction to tourism 110', 'EBIT'),
                        (2, 'IMY 110', 'Introduction to web technologies 110', 'EBIT'),
                        (2, 'GTS 161', 'Introductory genetics 161', 'EBIT'),
                        (2, 'GGY 283', 'Introductory geographic information systems 283', 'EBIT'),
                        (2, 'NDE 210', 'isiNdebele 210', 'EBIT'),
                        (2, 'NDE 310', 'isiNdebele 310', 'EBIT'),
                        (2, 'ZUL 310', 'isiZulu 310', 'EBIT'),
                        (2, 'ZUL 211', 'IsiZulu grammar – Capita selecta 211', 'EBIT'),
                        (2, 'CKN 321', 'Kinetics 321', 'EBIT'),
                        (2, 'CLB 321', 'Laboratory 321', 'EBIT'),
                        (2, 'ABR 311', 'Labour law 311', 'EBIT'),
                        (2, 'ABV 320', 'Labour relations 320', 'EBIT'),
                        (2, 'WTW 146', 'Linear algebra 146', 'EBIT'),
                        (2, 'ELI 220', 'Linear systems 220', 'EBIT'),
                        (2, 'MOW 312', 'Machine design 312', 'EBIT'),
                        (2, 'MII 420', 'Maintenance engineering 420', 'EBIT'),
                        (2, 'BSR 410', 'Management accounting 410', 'EBIT'),
                        (2, 'MOW 217', 'Manufacturing and design 217', 'EBIT'),
                        (2, 'MVS 311', 'Manufacturing systems 311', 'EBIT'),
                        (2, 'BEM 120', 'Marketing management 120', 'EBIT'),
                        (2, 'BEM 321', 'Marketing management 321', 'EBIT'),
                        (2, 'CMO 310', 'Mass transfer 310', 'EBIT'),
                        (2, 'NMC 113', 'Materials science 113', 'EBIT'),
                        (2, 'NMC 123', 'Materials science 123', 'EBIT'),
                        (2, 'NMC 223', 'Materials science 223', 'EBIT'),
                        (2, 'NMC 313', 'Materials science 313', 'EBIT'),
                        (2, 'WTW 152', 'Mathematical modelling 152', 'EBIT'),
                        (2, 'WST 111', 'Mathematical statistics 111', 'EBIT'),
                        (2, 'WST 121', 'Mathematical statistics 121', 'EBIT'),
                        (2, 'WST 211', 'Mathematical statistics 211', 'EBIT'),
                        (2, 'WST 221', 'Mathematical statistics 221', 'EBIT'),
                        (2, 'WTW 124', 'Mathematics 124', 'EBIT'),
                        (2, 'WTW 134', 'Mathematics 134', 'EBIT'),
                        (2, 'WTW 164', 'Mathematics 164', 'EBIT'),
                        (2, 'WTW 238', 'Mathematics 238', 'EBIT'),
                        (2, 'NMM 320', 'Mechanical metallurgy 320', 'EBIT'),
                        (2, 'MBB 410', 'Mechatronics and control 410', 'EBIT'),
                        (2, 'NTC 210', 'Metallurgical calculations 210', 'EBIT'),
                        (2, 'NTV 310', 'Metallurgical fluid mechanics 310', 'EBIT'),
                        (2, 'NPW 411', 'Metals processing 411', 'EBIT'),
                        (2, 'EMK 310', 'Microprocessors 310', 'EBIT'),
                        (2, 'EMZ 320', 'Microwaves and antennas 320', 'EBIT'),
                        (2, 'PMZ 422', 'Mine design and research 422', 'EBIT'),
                        (2, 'PMW 410', 'Mine evaluation 410', 'EBIT'),
                        (2, 'PMY 423', 'Mine operational risk management 423', 'EBIT'),
                        (2, 'PEE 410', 'Mine ventilation engineering 410', 'EBIT'),
                        (2, 'GMI 210', 'Mineralogy 210', 'EBIT'),
                        (2, 'NMP 310', 'Minerals processing 310', 'EBIT'),
                        (2, 'NMP 411', 'Minerals processing 411', 'EBIT'),
                        (2, 'PMY 320', 'Mining 320', 'EBIT'),
                        (2, 'PMY 410', 'Mining 410', 'EBIT'),
                        (2, 'PMY 220', 'Mining technology 220', 'EBIT'),
                        (2, 'ENG 210', 'Modern English literature and English studies 210', 'EBIT'),
                        (2, 'EMS 310', 'Modulation systems 310', 'EBIT'),
                        (2, 'MLB 111', 'Molecular and cell biology 111', 'EBIT'),
                        (2, 'GTS 251', 'Molecular genetics 251', 'EBIT'),
                        (2, 'IMY 320', 'Multimedia 320', 'EBIT'),
                        (2, 'IMY 300', 'Multimedia: Project 300', 'EBIT'),
                        (2, 'TPD 220', 'Municipal development planning 220', 'EBIT'),
                        (2, 'TPS 322', 'Municipal services provision 322', 'EBIT'),
                        (2, 'MCS 200', 'Music technology 200', 'EBIT'),
                        (2, 'MCS 302', 'Music technology 302', 'EBIT'),
                        (2, 'MCS 402', 'Music technology 402', 'EBIT'),
                        (2, 'MGS 100', 'Musicology 100', 'EBIT'),
                        (2, 'MBY 261', 'Mycology 261', 'EBIT'),
                        (2, 'COS 216', 'Netcentric computer systems 216', 'EBIT'),
                        (2, 'MKI 420', 'Nuclear engineering 420', 'EBIT'),
                        (2, 'WTW 123', 'Numerical analysis 123', 'EBIT'),
                        (2, 'WTW 263', 'Numerical methods 263', 'EBIT'),
                        (2, 'COS 122', 'Operating systems 122', 'EBIT'),
                        (2, 'BOZ 312', 'Operational research 312', 'EBIT'),
                        (2, 'BON 410', 'Operational research 410', 'EBIT'),
                        (2, 'MOO 420', 'Optimum design 420', 'EBIT'),
                        (2, 'CPA 410', 'Particle technology 410', 'EBIT'),
                        (2, 'SGM 221', 'Pavement materials and design 221', 'EBIT'),
                        (2, 'FSK 116', 'Physics 116', 'EBIT'),
                        (2, 'FSK 176', 'Physics 176', 'EBIT'),
                        (2, 'PHY 131', 'Physics for biology students 131', 'EBIT'),
                        (2, 'TPA 210', 'Plan and policy analysis and assessment 210', 'EBIT'),
                        (2, 'TPH 110', 'Planning and settlement histories before the Industrial Revolution 110', 'EBIT'),
                        (2, 'TPH 120', 'Planning and settlement histories since the Industrial Revolution 120', 'EBIT'),
                        (2, 'TPI 453', 'Planning interventions: Metropolitan scale 453', 'EBIT'),
                        (2, 'TPI 452', 'Planning interventions: Peri-urban and rural scale 452', 'EBIT'),
                        (2, 'TPI 451', 'Planning interventions: Precinct scale 451', 'EBIT'),
                        (2, 'TPI 454', 'Planning interventions: Supranational, national and provincial scale 454', 'EBIT'),
                        (2, 'TRP 320', 'Planning prospects 320', 'EBIT'),
                        (2, 'BTC 361', 'Plant genetics and crop biotechnology 361', 'EBIT'),
                        (2, 'BOT 161', 'Plants and society 161', 'EBIT'),
                        (2, 'GTS 367', 'Population and evolutionary genetics 367', 'EBIT'),
                        (2, 'EDF 320', 'Power electronics 320', 'EBIT'),
                        (2, 'EKK 410', 'Power system analysis 410', 'EBIT'),
                        (2, 'EKK 320', 'Power system components 320', 'EBIT'),
                        (2, 'BPY 310', 'Practical training 310', 'EBIT'),
                        (2, 'CPY 311', 'Practical training 311', 'EBIT'),
                        (2, 'MPY 315', 'Practical training 315', 'EBIT'),
                        (2, 'SPY 410', 'Practical training 410', 'EBIT'),
                        (2, 'BPY 410', 'Practical training 410', 'EBIT'),
                        (2, 'CPY 411', 'Practical training 411', 'EBIT'),
                        (2, 'MPY 415', 'Practical training 415', 'EBIT'),
                        (2, 'EPY 423', 'Practical training and report 423', 'EBIT'),
                        (2, 'EPW 200', 'Practical wiring 200', 'EBIT'),
                        (2, 'PJS 310', 'Practice management 310', 'EBIT'),
                        (2, 'TPS 120', 'Principles of settlement design 120', 'EBIT'),
                        (2, 'CPS 420', 'Process analysis 420', 'EBIT'),
                        (2, 'CPB 410', 'Process control 410', 'EBIT'),
                        (2, 'NOP 421', 'Process design 421', 'EBIT'),
                        (2, 'CPN 321', 'Process dynamics 321', 'EBIT'),
                        (2, 'NPB 312', 'Process heat transfer and control 312', 'EBIT'),
                        (2, 'CPS 410', 'Process synthesis 410', 'EBIT'),
                        (2, 'NPT 220', 'Process thermodynamics 220', 'EBIT'),
                        (2, 'BPZ 220', 'Productivity 220', 'EBIT'),
                        (2, 'NJJ 210', 'Professional and technical communication 210', 'EBIT'),
                        (2, 'BJJ 210', 'Professional and technical communication 210', 'EBIT'),
                        (2, 'MJJ 210', 'Professional and technical communication 210', 'EBIT'),
                        (2, 'EJJ 210', 'Professional and technical communication 210', 'EBIT'),
                        (2, 'PJJ 210', 'Professional and technical communication 210', 'EBIT'),
                        (2, 'CJJ 310', 'Professional and technical communication 310', 'EBIT'),
                        (2, 'JPO 110', 'Professional orientation 110', 'EBIT'),
                        (2, 'JPO 120', 'Professional orientation 120', 'EBIT'),
                        (2, 'TRP 412', 'Professional practice 412', 'EBIT'),
                        (2, 'COS 110', 'Program design: Introduction 110', 'EBIT'),
                        (2, 'MPR 213', 'Programming and information technology 213', 'EBIT'),
                        (2, 'COS 333', 'Programming languages 333', 'EBIT'),
                        (2, 'EPR 400', 'Project 400', 'EBIT'),
                        (2, 'EPR 402', 'Project 402', 'EBIT'),
                        (2, 'BPJ 410', 'Project 410', 'EBIT'),
                        (2, 'PSC 411', 'Project 411', 'EBIT'),
                        (2, 'BPJ 420', 'Project 420', 'EBIT'),
                        (2, 'EOW 222', 'Property law 222', 'EBIT'),
                        (2, 'EDW 300', 'Property valuation 300', 'EBIT'),
                        (2, 'SLK 110', 'Psychology 110', 'EBIT'),
                        (2, 'SLK 120', 'Psychology 120', 'EBIT'),
                        (2, 'PAD 112', 'Public administration 112', 'EBIT'),
                        (2, 'PAD 122', 'Public administration 122', 'EBIT'),
                        (2, 'PUB 120', 'Publishing 120', 'EBIT'),
                        (2, 'PUB 210', 'Publishing 210', 'EBIT'),
                        (2, 'PUB 220', 'Publishing 220', 'EBIT'),
                        (2, 'PUB 310', 'Publishing 310', 'EBIT'),
                        (2, 'PUB 311', 'Publishing 311', 'EBIT'),
                        (2, 'PUB 320', 'Publishing 320', 'EBIT'),
                        (2, 'PUB 321', 'Publishing 321', 'EBIT'),
                        (2, 'PUB 110', 'Publishing: Introduction to publishing 110', 'EBIT'),
                        (2, 'NPM 321', 'Pyrometallurgy 321', 'EBIT'),
                        (2, 'BGC 410', 'Quality assurance 410', 'EBIT'),
                        (2, 'HVH 101', 'Quantities 101', 'EBIT'),
                        (2, 'HVH 200', 'Quantities 200', 'EBIT'),
                        (2, 'HVH 300', 'Quantities 300', 'EBIT'),
                        (2, 'BRK 300', 'Quantity surveying practice 300', 'EBIT'),
                        (2, 'CRO 410', 'Reactor design 410', 'EBIT'),
                        (2, 'EWS 110', 'Real estate 110', 'EBIT'),
                        (2, 'EWS 120', 'Real estate 120', 'EBIT'),
                        (2, 'EWS 210', 'Real estate 210', 'EBIT'),
                        (2, 'EWS 220', 'Real estate 220', 'EBIT'),
                        (2, 'EWS 310', 'Real estate 310', 'EBIT'),
                        (2, 'EWS 320', 'Real estate 320', 'EBIT'),
                        (2, 'NVM 321', 'Refractory materials 321', 'EBIT'),
                        (2, 'TPD 310', 'Regional development planning 310', 'EBIT'),
                        (2, 'SIN 324', 'Reinforced concrete design 324', 'EBIT'),
                        (2, 'SIN 413', 'Reinforced concrete design 413', 'EBIT'),
                        (2, 'GMA 220', 'Remote sensing 220', 'EBIT'),
                        (2, 'TPE 410', 'Research methodology 410', 'EBIT'),
                        (2, 'NSC 400', 'Research project 400', 'EBIT'),
                        (2, 'CSC 411', 'Research project 411', 'EBIT'),
                        (2, 'SSC 412', 'Research project 412', 'EBIT'),
                        (2, 'MRN 412', 'Research project 412', 'EBIT'),
                        (2, 'ERP 420', 'Research project 420', 'EBIT'),
                        (2, 'ENR 420', 'Research project 420', 'EBIT'),
                        (2, 'CSC 421', 'Research project 421', 'EBIT'),
                        (2, 'MRN 422', 'Research project 422', 'EBIT'),
                        (2, 'EES 424', 'Research project 424', 'EBIT'),
                        (2, 'TPE 420', 'Research report 420', 'EBIT'),
                        (2, 'OBS 214', 'Responsible management 214', 'EBIT'),
                        (2, 'ERB 410', 'Robotics 410', 'EBIT'),
                        (2, 'EPR 405', 'Robotics Project 405', 'EBIT'),
                        (2, 'PRX 321', 'Rock breaking 321', 'EBIT'),
                        (2, 'PSZ 410', 'Rock engineering 410', 'EBIT'),
                        (2, 'TPD 320', 'Rural development planning 320', 'EBIT'),
                        (2, 'SEP 310', 'Sepedi 310', 'EBIT'),
                        (2, 'SEP 211', 'Sepedi grammar – Capita selecta 211', 'EBIT'),
                        (2, 'TPA 120', 'Settlement analysis and assessment 120', 'EBIT'),
                        (2, 'TPS 210', 'Settlement design concepts 210', 'EBIT'),
                        (2, 'TPS 220', 'Settlement establishment planning and housing delivery 220', 'EBIT'),
                        (2, 'BUY 321', 'Simulation modelling 321', 'EBIT'),
                        (2, 'MOW 323', 'Simulation-based design 323', 'EBIT'),
                        (2, 'TPA 110', 'Site analysis and assessment 110', 'EBIT'),
                        (2, 'TRN 213', 'Site surveying 213', 'EBIT'),
                        (2, 'SOC 110', 'Sociology 110', 'EBIT'),
                        (2, 'SOC 120', 'Sociology 120', 'EBIT'),
                        (2, 'SOC 211', 'Sociology 211', 'EBIT'),
                        (2, 'SOC 221', 'Sociology 221', 'EBIT'),
                        (2, 'SOC 310', 'Sociology 310', 'EBIT'),
                        (2, 'SOC 321', 'Sociology 321', 'EBIT'),
                        (2, 'COS 301', 'Software engineering 301', 'EBIT'),
                        (2, 'EPE 321', 'Software engineering 321', 'EBIT'),
                        (2, 'COS 214', 'Software modelling 214', 'EBIT'),
                        (2, 'SGM 311', 'Soil mechanics 311', 'EBIT'),
                        (2, 'MKM 321', 'Solid mechanics 321', 'EBIT'),
                        (2, 'GGY 166', 'Southern African geomorphology 166', 'EBIT'),
                        (2, 'GIS 320', 'Spatial analysis 320', 'EBIT'),
                        (2, 'TPS 310', 'Spatial concepts 310', 'EBIT'),
                        (2, 'CSS 420', 'Specialisation: Analytical techniques 420', 'EBIT'),
                        (2, 'CSS 421', 'Specialisation: Environmental engineering 421', 'EBIT'),
                        (2, 'CSS 422', 'Specialisation: Polymer processing 422', 'EBIT'),
                        (2, 'CSS 423', 'Specialisation: Sustainable chemical engineering practices 423', 'EBIT'),
                        (2, 'SWK 122', 'Statics 122', 'EBIT'),
                        (2, 'STK 110', 'Statistics 110', 'EBIT'),
                        (2, 'STK 120', 'Statistics 120', 'EBIT'),
                        (2, 'STC 121', 'Statistics 121', 'EBIT'),
                        (2, 'STC 122', 'Statistics 122', 'EBIT'),
                        (2, 'STC 152', 'Statistics 152', 'EBIT'),
                        (2, 'STK 210', 'Statistics 210', 'EBIT'),
                        (2, 'STK 220', 'Statistics 220', 'EBIT'),
                        (2, 'STK 310', 'Statistics 310', 'EBIT'),
                        (2, 'SIN 323', 'Steel design 323', 'EBIT'),
                        (2, 'SIN 411', 'Steel design 411', 'EBIT'),
                        (2, 'ESC 320', 'Stochastic communications systems 320', 'EBIT'),
                        (2, 'PSZ 310', 'Strata control 310', 'EBIT'),
                        (2, 'SWK 210', 'Strength of materials 210', 'EBIT'),
                        (2, 'SWK 211', 'Strength of materials II 211', 'EBIT'),
                        (2, 'SIN 223', 'Structural analysis 223', 'EBIT'),
                        (2, 'SIN 311', 'Structural analysis 311', 'EBIT'),
                        (2, 'MOW 227', 'Structural design 227', 'EBIT'),
                        (2, 'MSY 310', 'Structural mechanics 310', 'EBIT'),
                        (2, 'SKE 120', 'Structures 120', 'EBIT'),
                        (2, 'BOB 311', 'Supply chain engineering 311', 'EBIT'),
                        (2, 'BLK 321', 'Supply chain engineering 321', 'EBIT'),
                        (2, 'BFB 321', 'Supply chain technologies and project 321', 'EBIT'),
                        (2, 'PMY 311', 'Surface mining 311', 'EBIT'),
                        (2, 'SUR 220', 'Surveying 220', 'EBIT'),
                        (2, 'VKN 320', 'Sustainable construction 320', 'EBIT'),
                        (2, 'BSS 410', 'Systems engineering 410', 'EBIT'),
                        (2, 'BEL 200', 'Taxation 200', 'EBIT'),
                        (2, 'BEL 300', 'Taxation 300', 'EBIT'),
                        (2, 'STK 353', 'The science of data analytics 353', 'EBIT'),
                        (2, 'COS 210', 'Theoretical computer science 210', 'EBIT'),
                        (2, 'TPU 211', 'Theory and practice of land-use management 211', 'EBIT'),
                        (2, 'STU 123', 'Theory of structures 123', 'EBIT'),
                        (2, 'STU 211', 'Theory of structures 211', 'EBIT'),
                        (2, 'STU 221', 'Theory of structures 221', 'EBIT'),
                        (2, 'MTV 420', 'Thermal and fluid machines 420', 'EBIT'),
                        (2, 'MTX 221', 'Thermodynamics 221', 'EBIT'),
                        (2, 'CTD 223', 'Thermodynamics 223', 'EBIT'),
                        (2, 'MTX 311', 'Thermodynamics 311', 'EBIT'),
                        (2, 'SIB 310', 'Timber design 310', 'EBIT'),
                        (2, 'COP 311', 'Transfer processes 311', 'EBIT'),
                        (2, 'TPS 321', 'Transport planning 321', 'EBIT'),
                        (2, 'SVC 323', 'Transportation engineering 323', 'EBIT'),
                        (2, 'ISB 311', 'Trends in human computer interface design 311', 'EBIT'),
                        (2, 'TPU 221', 'Urban land development economics 221', 'EBIT'),
                        (2, 'MVE 420', 'Vehicle engineering 420', 'EBIT'),
                        (2, 'MVR 320', 'Vibration and noise 320', 'EBIT'),
                        (2, 'VKK 111', 'Visual culture studies 111', 'EBIT'),
                        (2, 'VKK 211', 'Visual culture studies 211', 'EBIT'),
                        (2, 'VIO 102', 'Visual design (1) 102', 'EBIT'),
                        (2, 'VIO 202', 'Visual design (2) 202', 'EBIT'),
                        (2, 'ISB 301', 'Work based learning project 301', 'EBIT'),
                        (2, 'SWP 121', 'Workshop practice 121', 'EBIT'),
                        (2, 'WWP 121', 'Workshop practice 121', 'EBIT')
                    ON CONFLICT (course_code) DO NOTHING;
                    "
            );
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<string>(
                name: "faculty",
                schema: "unitrade",
                table: "courses",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text"
            );
            migrationBuilder.Sql(@"DELETE FROM unitrade.courses WHERE university_id = 2;");
        }
    }
}
