// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901201207_AddSavedSearchToNotificationType")]
    partial class AddSavedSearchToNotificationType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("unitrade")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Audit.Models.AuditLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("LogId")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_audit_actor");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_audit_created");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_entity");

                    b.ToTable("audit_logs", "unitrade");
                });

            modelBuilder.Entity("Modules.Chat.Models.ChatMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("message_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<string>("ClientKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("client_key");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("text")
                        .HasColumnName("message_type");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("MessageId")
                        .HasName("pk_chat_messages");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_chat_messages_sender_id");

                    b.HasIndex("ReservationId", "ClientKey")
                        .IsUnique()
                        .HasDatabaseName("uix_chat_client_key")
                        .HasFilter("client_key IS NOT NULL");

                    b.HasIndex("ReservationId", "ReadAt")
                        .HasDatabaseName("ix_chat_unread")
                        .HasFilter("read_at IS NULL");

                    b.HasIndex("ReservationId", "SentAt")
                        .HasDatabaseName("ix_chat_reservation");

                    b.ToTable("chat_messages", "unitrade", t =>
                        {
                            t.HasCheckConstraint("chk_message_type", "message_type IN ('text', 'system', 'meetup_proposal',  'meetup_response')");

                            t.HasCheckConstraint("chk_payload_type", "(message_type IN ('meetup_proposal', 'meetup_response') AND payload IS NOT NULL ) OR( message_type IN ('text', 'system')  AND payload IS NULL )");

                            t.HasCheckConstraint("chk_system_sender", "(message_type = 'system' AND sender_id IS NULL) OR (message_type <> 'system' AND sender_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Modules.Disputes.Models.Dispute", b =>
                {
                    b.Property<Guid>("DisputeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("dispute_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssignedAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_admin_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<int?>("MeetupId")
                        .HasColumnType("integer")
                        .HasColumnName("meetup_id");

                    b.PrimitiveCollection<List<string>>("Photos")
                        .HasColumnType("text[]")
                        .HasColumnName("photos");

                    b.Property<Guid?>("RaisedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("raised_by");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<string>("Resolution")
                        .HasColumnType("text")
                        .HasColumnName("resolution");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<bool>("SellerRefusedPhotos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("seller_refused_photos");

                    b.Property<Guid?>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_user_id");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("DisputeId")
                        .HasName("pk_disputes");

                    b.HasIndex("AssignedAdminId")
                        .HasDatabaseName("ix_disputes_assigned_admin_id");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_disputes_listing_id");

                    b.HasIndex("MeetupId")
                        .HasDatabaseName("ix_disputes_meetup_id");

                    b.HasIndex("RaisedBy")
                        .HasDatabaseName("ix_disputes_raised_by");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("ix_disputes_reservation_id");

                    b.HasIndex("SnapshotId")
                        .HasDatabaseName("ix_disputes_snapshot_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_disputes_status");

                    b.HasIndex("SubjectUserId")
                        .HasDatabaseName("ix_disputes_subject");

                    b.HasIndex("SubmittedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_disputes_submitted");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_disputes_type");

                    b.ToTable("disputes", "unitrade", t =>
                        {
                            t.HasCheckConstraint("chk_dispute_status", "status IN ('open','under_review','resolved','closed')");

                            t.HasCheckConstraint("chk_dispute_type", "type IN ('listing_quality','report_listing','no_show')");
                        });
                });

            modelBuilder.Entity("Modules.Identity.Models.AdminProfile", b =>
                {
                    b.Property<Guid>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<int>("UniversityId")
                        .HasColumnType("integer")
                        .HasColumnName("university_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("AdminId")
                        .HasName("pk_admin_profiles");

                    b.HasIndex("UniversityId")
                        .HasDatabaseName("ix_admin_profiles_university_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_profiles_user_id");

                    b.ToTable("admin_profiles", "unitrade");
                });

            modelBuilder.Entity("Modules.Identity.Models.ProofOfRegistrationDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("file_data");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int>("FileSize")
                        .HasColumnType("integer")
                        .HasColumnName("file_size");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("VerificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("verification_id");

                    b.HasKey("DocumentId")
                        .HasName("pk_proof_of_registration_documents");

                    b.HasIndex("VerificationId")
                        .IsUnique()
                        .HasDatabaseName("uix_por_verification");

                    b.ToTable("proof_of_registration_documents", "unitrade");
                });

            modelBuilder.Entity("Modules.Identity.Models.StudentProfile", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<decimal>("BuyerReliabilityScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("buyer_reliability_score");

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<string>("DegreeProgram")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("degree_program");

                    b.Property<decimal>("SellerTrustScore")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("seller_trust_score");

                    b.Property<string>("StudentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("student_number");

                    b.Property<int>("UniversityId")
                        .HasColumnType("integer")
                        .HasColumnName("university_id");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("verification_status");

                    b.Property<int>("YearOfStudy")
                        .HasColumnType("integer")
                        .HasColumnName("year_of_study");

                    b.HasKey("StudentId")
                        .HasName("pk_student_profiles");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_student_course");

                    b.HasIndex("UniversityId")
                        .HasDatabaseName("ix_student_university");

                    b.HasIndex("VerificationStatus")
                        .HasDatabaseName("ix_student_status");

                    b.ToTable("student_profiles", "unitrade", t =>
                        {
                            t.HasCheckConstraint("chk_student_verification", "verification_status IN ('pending', 'partial', 'verified', 'rejected')");

                            t.HasCheckConstraint("chk_student_year", "year_of_study BETWEEN 1 AND 8");
                        });
                });

            modelBuilder.Entity("Modules.Identity.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terms_accepted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", "unitrade", t =>
                        {
                            t.HasTrigger("tr_users_updated_at");

                            t.HasCheckConstraint("chk_user_role", "role IN ('student', 'admin')");
                        });
                });

            modelBuilder.Entity("Modules.Identity.Models.VerificationRequest", b =>
                {
                    b.Property<Guid>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("verification_id");

                    b.Property<string>("AdminDecision")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("admin_decision");

                    b.Property<Guid?>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<decimal?>("AiConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ai_confidence_score");

                    b.Property<string>("AiDecision")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ai_decision");

                    b.Property<int>("AttemptNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_number");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("OtpCodeHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("otp_code_hash");

                    b.Property<DateTime>("OtpExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_expires_at");

                    b.Property<int?>("OtpResendCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("otp_resend_count");

                    b.Property<DateTime?>("OtpSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_sent_at");

                    b.Property<DateTime?>("OtpVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_verified_at");

                    b.Property<string>("PorFilePath")
                        .HasColumnType("text")
                        .HasColumnName("por_file_path");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("otp_pending")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int?>("TotalAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_attempt_count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("VerificationId")
                        .HasName("pk_verification_requests");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_vr_status");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uix_vr_current")
                        .HasFilter("is_current = true");

                    b.ToTable("verification_requests", "unitrade", t =>
                        {
                            t.HasTrigger("tr_audit_verification_decision");

                            t.HasTrigger("tr_verification_set_current");

                            t.HasCheckConstraint("chk_vr_status", "status IN ('otp_pending', 'por_pending','under_review','approved', 'rejected')");
                        });
                });

            modelBuilder.Entity("Modules.Listings.Models.BookDetails", b =>
                {
                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<string>("Author")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("author");

                    b.Property<string>("Edition")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("edition");

                    b.Property<string>("Isbn")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("isbn");

                    b.HasKey("ListingId")
                        .HasName("pk_book_details");

                    b.ToTable("book_details", "unitrade", t =>
                        {
                            t.HasCheckConstraint("chk_isbn_validity", "isbn IS NULL OR length(isbn) IN  (10,13)");
                        });
                });

            modelBuilder.Entity("Modules.Listings.Models.Listing", b =>
                {
                    b.Property<Guid>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiRiskLevel")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ai_risk_level");

                    b.Property<decimal?>("AiRiskScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ai_risk_score");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("condition");

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<int?>("CourseId1")
                        .HasColumnType("integer")
                        .HasColumnName("course_id1");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("IsBundle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_bundle");

                    b.Property<string>("ListingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("listing_status");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.Property<int?>("VisibilityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("visibility_score");

                    b.HasKey("ListingId")
                        .HasName("pk_listings");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_listings_category");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_listings_course");

                    b.HasIndex("CourseId1")
                        .HasDatabaseName("ix_listings_course_id1");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_listings_seller");

                    b.HasIndex("CategoryId", "ListingStatus", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_listings_category_browse")
                        .HasFilter("listing_status = 'live'");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CategoryId", "ListingStatus", "CreatedAt"), new[] { "Title", "Price", "SellerId" });

                    b.HasIndex("CourseId", "ListingStatus", "CreatedAt")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_listings_course_browse")
                        .HasFilter("listing_status = 'live'");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CourseId", "ListingStatus", "CreatedAt"), new[] { "Title", "Price", "SellerId", "CategoryId" });

                    b.HasIndex("ListingStatus", "VisibilityScore", "CreatedAt")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_listings_feed")
                        .HasFilter("listing_status = 'live'");

                    b.ToTable("listings", "unitrade", t =>
                        {
                            t.HasTrigger("tr_listings_updated_at");

                            t.HasCheckConstraint("chk_listing_condition", "condition IN ('new', 'good', 'fair', 'poor')");

                            t.HasCheckConstraint("chk_listing_price", "price > 0");

                            t.HasCheckConstraint("chk_listing_risk", "ai_risk_level IS NULL OR ai_risk_level IN ('low', 'medium', 'high')");

                            t.HasCheckConstraint("chk_listing_status", "listing_status IN ('draft', 'pending', 'live', 'reserved', 'low_visibility', 'rejected', 'sold', 'removed')");
                        });
                });

            modelBuilder.Entity("Modules.Listings.Models.ListingCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId")
                        .HasName("pk_listing_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_listing_categories_name");

                    b.ToTable("listing_categories", "unitrade");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            IsActive = true,
                            Name = "book"
                        },
                        new
                        {
                            CategoryId = 2,
                            IsActive = true,
                            Name = "electronics"
                        },
                        new
                        {
                            CategoryId = 3,
                            IsActive = true,
                            Name = "stationery"
                        },
                        new
                        {
                            CategoryId = 4,
                            IsActive = true,
                            Name = "furniture"
                        },
                        new
                        {
                            CategoryId = 5,
                            IsActive = true,
                            Name = "clothing"
                        },
                        new
                        {
                            CategoryId = 6,
                            IsActive = true,
                            Name = "other"
                        });
                });

            modelBuilder.Entity("Modules.Listings.Models.ListingImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("image_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<int>("FileSize")
                        .HasColumnType("integer")
                        .HasColumnName("file_size");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("image_data");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ImageId")
                        .HasName("pk_listing_images");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_listing_images_listing");

                    b.ToTable("listing_images", "unitrade");
                });

            modelBuilder.Entity("Modules.Listings.Models.ListingSnapshot", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<DateTime>("CapturedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("condition");

                    b.PrimitiveCollection<List<string>>("CourseTags")
                        .HasColumnType("text[]")
                        .HasColumnName("course_tags");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.PrimitiveCollection<List<string>>("PhotoRefs")
                        .HasColumnType("text[]")
                        .HasColumnName("photo_refs");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.HasKey("SnapshotId")
                        .HasName("pk_listing_snapshot");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_listing_snapshots_listing_id");

                    b.HasIndex("ReservationId")
                        .IsUnique()
                        .HasDatabaseName("ix_listing_snapshot_reservation_id");

                    b.ToTable("listing_snapshot", "unitrade", t =>
                        {
                            t.HasCheckConstraint("chk_listing_snapshot_price", "price > 0");
                        });
                });

            modelBuilder.Entity("Modules.Notifications.Models.DeviceToken", b =>
                {
                    b.Property<Guid>("DeviceTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("device_token_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("platform");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("DeviceTokenId")
                        .HasName("pk_device_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_device_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_device_tokens_user");

                    b.ToTable("device_tokens", "unitrade", t =>
                        {
                            t.HasCheckConstraint("chk_device_platform", "platform IN ('web', 'android', 'ios')");
                        });
                });

            modelBuilder.Entity("Modules.Notifications.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notification_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notif_user_unread")
                        .HasFilter("is_read = false");

                    b.ToTable("notifications", "unitrade", t =>
                        {
                            t.HasCheckConstraint("chk_notif_type", "type IN ('listing_status', 'reservation_status', 'meetup_reminder',  'chat', 'dispute', 'verification')");
                        });
                });

            modelBuilder.Entity("Modules.ReferenceData.Course.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_code");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_name");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("faculty");

                    b.Property<int>("UniversityId")
                        .HasColumnType("integer")
                        .HasColumnName("university_id");

                    b.HasKey("CourseId")
                        .HasName("pk_courses");

                    b.HasIndex("CourseCode")
                        .IsUnique()
                        .HasDatabaseName("ix_courses_course_code");

                    b.HasIndex("UniversityId")
                        .HasDatabaseName("ix_courses_university_id");

                    b.ToTable("courses", "unitrade");
                });

            modelBuilder.Entity("Modules.ReferenceData.University.University", b =>
                {
                    b.Property<int>("UniversityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("university_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UniversityId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("UniversityId")
                        .HasName("pk_universities");

                    b.ToTable("universities", "unitrade");
                });

            modelBuilder.Entity("Modules.ReferenceData.University.UniversityEmailDomain", b =>
                {
                    b.Property<int>("DomainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("domain_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DomainId"));

                    b.Property<string>("EmailDomain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_domain");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("UniversityId")
                        .HasColumnType("integer")
                        .HasColumnName("university_id");

                    b.HasKey("DomainId")
                        .HasName("pk_university_email_domains");

                    b.HasIndex("EmailDomain")
                        .IsUnique()
                        .HasDatabaseName("ix_university_email_domains_email_domain");

                    b.HasIndex("UniversityId")
                        .HasDatabaseName("ix_university_email_domains_university_id");

                    b.ToTable("university_email_domains", "unitrade");
                });

            modelBuilder.Entity("Modules.Reputation.Models.Strike", b =>
                {
                    b.Property<Guid>("StrikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("strike_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_admin_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("SourceCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_case_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("StrikeId")
                        .HasName("pk_strikes");

                    b.HasIndex("CreatedByAdminId")
                        .HasDatabaseName("ix_strikes_created_by_admin");

                    b.HasIndex("SourceCaseId")
                        .HasDatabaseName("ix_strikes_source_case");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_strikes_user");

                    b.ToTable("strikes", "unitrade");
                });

            modelBuilder.Entity("Modules.Reservations.Models.Meetup", b =>
                {
                    b.Property<int>("MeetupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("meetup_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MeetupId"));

                    b.Property<decimal>("AgreedLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("agreed_latitude");

                    b.Property<string>("AgreedLocationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("agreed_location_name");

                    b.Property<decimal>("AgreedLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("agreed_longitude");

                    b.Property<DateTime>("AgreedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("agreed_time");

                    b.Property<bool>("BuyerCheckedIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("buyer_checked_in");

                    b.Property<DateTime?>("BuyerCheckedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("buyer_checked_in_at");

                    b.Property<decimal?>("BuyerCheckinLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("buyer_checkin_latitude");

                    b.Property<decimal?>("BuyerCheckinLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("buyer_checkin_longitude");

                    b.Property<DateTime?>("BuyerCheckinTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("buyer_checkin_time");

                    b.Property<DateTime>("CheckinWindowClosesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checkin_window_closes_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<bool>("SellerCheckedIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("seller_checked_in");

                    b.Property<DateTime?>("SellerCheckedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seller_checked_in_at");

                    b.Property<decimal?>("SellerCheckinLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("seller_checkin_latitude");

                    b.Property<decimal?>("SellerCheckinLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("seller_checkin_longitude");

                    b.Property<DateTime?>("SellerCheckinTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seller_checkin_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("MeetupId")
                        .HasName("pk_meetups");

                    b.HasIndex("ReservationId")
                        .IsUnique()
                        .HasDatabaseName("ix_meetup_reservation");

                    b.ToTable("meetups", "unitrade", t =>
                        {
                            t.HasCheckConstraint("chk_meetup_status", "status IN ('scheduled', 'completed', 'no_show_buyer', 'no_show_seller')");
                        });
                });

            modelBuilder.Entity("Modules.Reservations.Models.Reservation", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime?>("BuyerRespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("buyer_responded_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("HandoverConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handover_confirmed_at");

                    b.Property<bool>("IsBundle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_bundle");

                    b.Property<DateTime?>("MeetupConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("meetup_confirmed_at");

                    b.Property<string>("ReservationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reservation_status");

                    b.Property<DateTime?>("SellerAcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seller_acknowledged_at");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<DateTime?>("TwoHourWarningSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("two_hour_warning_sent_at");

                    b.HasKey("ReservationId")
                        .HasName("pk_reservations");

                    b.HasIndex("BuyerId")
                        .HasDatabaseName("ix_res_buyer");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_res_expires")
                        .HasFilter("reservation_status = 'active' AND meetup_confirmed_at IS NULL");

                    b.HasIndex("ReservationStatus")
                        .HasDatabaseName("ix_res_status");

                    b.HasIndex("SellerId")
                        .HasDatabaseName("ix_res_seller");

                    b.ToTable("reservations", "unitrade", t =>
                        {
                            t.HasCheckConstraint("chk_res_status", "reservation_status IN ('active', 'expired', 'cancelled', 'completed')");
                        });
                });

            modelBuilder.Entity("Modules.Reservations.Models.ReservationListing", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.HasKey("ReservationId", "ListingId")
                        .HasName("pk_reservation_listings");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_reservation_listings_listing_id");

                    b.ToTable("reservation_listings", "unitrade");
                });

            modelBuilder.Entity("Modules.Reviews.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("review_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("ReviewType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("review_type");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewee_id");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("ReviewId")
                        .HasName("pk_reviews");

                    b.HasIndex("RevieweeId")
                        .HasDatabaseName("ix_review_reviewee");

                    b.HasIndex("TransactionId", "ReviewerId")
                        .IsUnique()
                        .HasDatabaseName("review_per_transaction");

                    b.ToTable("reviews", "unitrade", t =>
                        {
                            t.HasTrigger("tr_reputation_on_review");

                            t.HasCheckConstraint("chk_rating", "rating BETWEEN 1 AND 5");

                            t.HasCheckConstraint("chk_review_self", "reviewer_id <> reviewee_id");

                            t.HasCheckConstraint("chk_review_type", "review_type IN ('buyer_to_seller', 'seller_to_buyer')");
                        });
                });

            modelBuilder.Entity("Modules.SavedSearches.Models.SavedSearch", b =>
                {
                    b.Property<Guid>("SearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("search_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("max_price");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("min_price");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("query");

                    b.HasKey("SearchId")
                        .HasName("pk_saved_searches");

                    b.HasIndex("BuyerId")
                        .HasDatabaseName("ix_saved_searches_buyer_id");

                    b.ToTable("saved_searches", "unitrade");
                });

            modelBuilder.Entity("Modules.SharedKernel.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("image_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<int>("FileSize")
                        .HasColumnType("integer")
                        .HasColumnName("file_size");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("image_data");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ImageId")
                        .HasName("pk_images");

                    b.ToTable("images", "unitrade");
                });

            modelBuilder.Entity("Modules.Transactions.Models.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PayFastTransactionId")
                        .HasColumnType("text")
                        .HasColumnName("pay_fast_transaction_id");

                    b.Property<string>("Pin")
                        .HasColumnType("text")
                        .HasColumnName("pin");

                    b.Property<int>("PinAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("pin_attempts");

                    b.Property<DateTime?>("PinEnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pin_entered_at");

                    b.Property<string>("PinHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pin_hash");

                    b.Property<string>("PinStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("pending")
                        .HasColumnName("pin_status");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("transaction_status");

                    b.HasKey("TransactionId")
                        .HasName("pk_transactions");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("ix_transactions_reservation");

                    b.ToTable("transactions", "unitrade");
                });

            modelBuilder.Entity("Modules.Wishlist.Models.WishlistItem", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("wishlist_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WishlistId"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("SuppressedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suppressed_at");

                    b.Property<Guid?>("SuppressedByReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("suppressed_by_reservation_id");

                    b.HasKey("WishlistId")
                        .HasName("pk_wishlist_items");

                    b.HasIndex("ListingId")
                        .HasDatabaseName("ix_wishlist_items_listing_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_wishlist_student");

                    b.HasIndex("StudentId", "ListingId")
                        .IsUnique()
                        .HasDatabaseName("wishlist_entry");

                    b.ToTable("wishlist_items", "unitrade");
                });

            modelBuilder.Entity("Modules.Chat.Models.ChatMessage", b =>
                {
                    b.HasOne("Modules.Reservations.Models.Reservation", "Reservation")
                        .WithMany("Messages")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_reservations_reservation_id");

                    b.HasOne("Modules.Identity.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_chat_messages_users_sender_id");

                    b.Navigation("Reservation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Modules.Disputes.Models.Dispute", b =>
                {
                    b.HasOne("Modules.Identity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_disputes_users_assigned_admin_id");

                    b.HasOne("Modules.Listings.Models.Listing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_disputes_listings_listing_id");

                    b.HasOne("Modules.Reservations.Models.Meetup", null)
                        .WithMany()
                        .HasForeignKey("MeetupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_disputes_meetups_meetup_id");

                    b.HasOne("Modules.Identity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("RaisedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_disputes_users_raised_by");

                    b.HasOne("Modules.Reservations.Models.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_disputes_reservations_reservation_id");

                    b.HasOne("Modules.Listings.Models.ListingSnapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_disputes_listing_snapshot_snapshot_id");

                    b.HasOne("Modules.Identity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SubjectUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_disputes_users_subject_user_id");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Modules.Identity.Models.AdminProfile", b =>
                {
                    b.HasOne("Modules.ReferenceData.University.University", null)
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_profiles_universities_university_id");

                    b.HasOne("Modules.Identity.Models.User", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("Modules.Identity.Models.AdminProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Modules.Identity.Models.ProofOfRegistrationDocument", b =>
                {
                    b.HasOne("Modules.Identity.Models.VerificationRequest", null)
                        .WithOne()
                        .HasForeignKey("Modules.Identity.Models.ProofOfRegistrationDocument", "VerificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proof_of_registration_documents_verification_requests_verif");
                });

            modelBuilder.Entity("Modules.Identity.Models.StudentProfile", b =>
                {
                    b.HasOne("Modules.ReferenceData.Course.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_student_profiles_courses_course_id");

                    b.HasOne("Modules.Identity.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("Modules.Identity.Models.StudentProfile", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_profiles_users_student_id");

                    b.HasOne("Modules.ReferenceData.University.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_profiles_universities_university_id");

                    b.Navigation("University");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Modules.Identity.Models.VerificationRequest", b =>
                {
                    b.HasOne("Modules.Identity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verification_requests_users_user_id");
                });

            modelBuilder.Entity("Modules.Listings.Models.BookDetails", b =>
                {
                    b.HasOne("Modules.Listings.Models.Listing", "Listing")
                        .WithOne("BookDetails")
                        .HasForeignKey("Modules.Listings.Models.BookDetails", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_details_listings_listing_id");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Modules.Listings.Models.Listing", b =>
                {
                    b.HasOne("Modules.Listings.Models.ListingCategory", "Category")
                        .WithMany("Listings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_listings_listing_categories_category_id");

                    b.HasOne("Modules.ReferenceData.Course.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_listings_courses_course_id");

                    b.HasOne("Modules.ReferenceData.Course.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId1")
                        .HasConstraintName("fk_listings_courses_course_id1");

                    b.HasOne("Modules.Identity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_listings_users_seller_id");

                    b.Navigation("Category");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Modules.Listings.Models.ListingImage", b =>
                {
                    b.HasOne("Modules.Listings.Models.Listing", "Listing")
                        .WithMany("Images")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_listing_images_listings_listing_id");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Modules.Listings.Models.ListingSnapshot", b =>
                {
                    b.HasOne("Modules.Listings.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_listing_snapshot_listings_listing_id");

                    b.HasOne("Modules.Reservations.Models.Reservation", "Reservation")
                        .WithOne("ListingSnapshot")
                        .HasForeignKey("Modules.Listings.Models.ListingSnapshot", "ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_listing_snapshot_reservations_reservation_id");

                    b.Navigation("Listing");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Modules.Notifications.Models.DeviceToken", b =>
                {
                    b.HasOne("Modules.Identity.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Modules.Notifications.Models.Notification", b =>
                {
                    b.HasOne("Modules.Identity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");
                });

            modelBuilder.Entity("Modules.ReferenceData.Course.Course", b =>
                {
                    b.HasOne("Modules.ReferenceData.University.University", null)
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_courses_universities_university_id");
                });

            modelBuilder.Entity("Modules.ReferenceData.University.UniversityEmailDomain", b =>
                {
                    b.HasOne("Modules.ReferenceData.University.University", "University")
                        .WithMany("EmailDomains")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_university_email_domains_universities_university_id");

                    b.Navigation("University");
                });

            modelBuilder.Entity("Modules.Reputation.Models.Strike", b =>
                {
                    b.HasOne("Modules.Identity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_strikes_users_created_by_admin_id");

                    b.HasOne("Modules.Identity.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_strikes_users_user_id");
                });

            modelBuilder.Entity("Modules.Reservations.Models.Meetup", b =>
                {
                    b.HasOne("Modules.Reservations.Models.Reservation", "Reservation")
                        .WithMany("Meetups")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meetups_reservations_reservation_id");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Modules.Reservations.Models.Reservation", b =>
                {
                    b.HasOne("Modules.Identity.Models.User", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_users_buyer_id");

                    b.HasOne("Modules.Identity.Models.User", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_users_seller_id");

                    b.Navigation("Buyer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Modules.Reservations.Models.ReservationListing", b =>
                {
                    b.HasOne("Modules.Listings.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_listings_listings_listing_id");

                    b.HasOne("Modules.Reservations.Models.Reservation", "Reservation")
                        .WithMany("ReservationListings")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_listings_reservations_reservation_id");

                    b.Navigation("Listing");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Modules.Reviews.Models.Review", b =>
                {
                    b.HasOne("Modules.Transactions.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_transactions_transaction_id");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Modules.Transactions.Models.Transaction", b =>
                {
                    b.HasOne("Modules.Reservations.Models.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_reservations_reservation_id");
                });

            modelBuilder.Entity("Modules.Wishlist.Models.WishlistItem", b =>
                {
                    b.HasOne("Modules.Listings.Models.Listing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishlist_items_listings_listing_id");

                    b.HasOne("Modules.Identity.Models.StudentProfile", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wishlist_items_student_profiles_student_id");

                    b.Navigation("Listing");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Modules.Identity.Models.User", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("Modules.Listings.Models.Listing", b =>
                {
                    b.Navigation("BookDetails");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Modules.Listings.Models.ListingCategory", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("Modules.ReferenceData.University.University", b =>
                {
                    b.Navigation("EmailDomains");
                });

            modelBuilder.Entity("Modules.Reservations.Models.Reservation", b =>
                {
                    b.Navigation("ListingSnapshot");

                    b.Navigation("Meetups");

                    b.Navigation("Messages");

                    b.Navigation("ReservationListings");
                });
#pragma warning restore 612, 618
        }
    }
}
