#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE SCHEMA IF NOT EXISTS unitrade AUTHORIZATION ${POSTGRES_USER};
    
    DO \$\$
    BEGIN 
        IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${APP_USER}') THEN
            CREATE ROLE ${APP_USER} LOGIN PASSWORD '${APP_USER_PASSWORD}';
        END IF;
    END
    \$\$;

    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APP_USER};
    GRANT USAGE ON SCHEMA unitrade TO ${APP_USER};

    ALTER ROLE ${APP_USER} SET search_path = unitrade;

    ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA unitrade
        GRANT SELECT, UPDATE, INSERT, DELETE ON TABLES TO ${APP_USER};

    ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA unitrade
        GRANT USAGE, SELECT ON SEQUENCES TO ${APP_USER};
EOSQL