
from __future__ import annotations

import datetime
import hashlib
import os
from pathlib import Path

import yaml

NFR_DIR = Path(__file__).resolve().parent
EVIDENCE_DIR = NFR_DIR / "evidence"
MATRIX = NFR_DIR / "traceability.yml"
OUT_MD = NFR_DIR / "EVIDENCE.md"
SUMS = EVIDENCE_DIR / "SHA256SUMS"

STATUS_LABEL = {
    "pass": "✅ pass",
    "documented": "documented",
}


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def env(name: str, default: str) -> str:
    value = os.environ.get(name)
    return value if value else default


def md_escape(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def verification_cell(req: dict) -> str:
    bits = []
    if req.get("tool"):
        bits.append(f"**{md_escape(req['tool'])}**")
    if req.get("test"):
        bits.append(f"`{md_escape(req['test'])}`")
    return "<br>".join(bits) if bits else "—"


def evidence_cell(req: dict) -> str:
    ev = req.get("evidence", {}) or {}
    parts = []
    path = ev.get("path")
    if isinstance(path, list):
        parts += [f"`{md_escape(p)}`" for p in path]
    elif path:
        parts.append(f"`{md_escape(path)}`")
    if ev.get("workflow"):
        parts.append(f"CI: {md_escape(ev['workflow'])}")
    if ev.get("artifact"):
        parts.append(f"artifact: `{md_escape(ev['artifact'])}`")
    link = ev.get("link")
    if link and not str(link).startswith("TODO"):
        parts.append(f"[link]({link})")
    return "<br>".join(parts) if parts else "—"


def main() -> None:
    repo = env("GITHUB_REPOSITORY", "local/UniTrade")
    sha = env("GITHUB_SHA", "local-uncommitted")
    ref = env("GITHUB_REF_NAME", "local")
    run_id = env("GITHUB_RUN_ID", "")
    server = env("GITHUB_SERVER_URL", "https://github.com")
    run_url = f"{server}/{repo}/actions/runs/{run_id}" if run_id else "_(local run — no CI run URL)_"
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    if not MATRIX.exists():
        raise SystemExit(f"traceability matrix not found at {MATRIX}")

    # 1) hash the evidence tree (skip the sums file itself)
    EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)
    files = sorted(
        p for p in EVIDENCE_DIR.rglob("*")
        if p.is_file() and p.name != "SHA256SUMS"
    )
    sum_lines = [f"{sha256(p)}  {p.relative_to(EVIDENCE_DIR).as_posix()}" for p in files]
    SUMS.write_text(("\n".join(sum_lines) + "\n") if sum_lines else "", encoding="utf-8")

    matrix_hash = sha256(MATRIX)

    # 2) load the matrix
    data = yaml.safe_load(MATRIX.read_text(encoding="utf-8")) or {}
    reqs = data.get("requirements", [])

    # tally
    counts: dict[str, int] = {}
    for r in reqs:
        counts[r.get("status", "?")] = counts.get(r.get("status", "?"), 0) + 1
    tally = " · ".join(f"{STATUS_LABEL.get(k, k)}: {v}" for k, v in sorted(counts.items()))

    # 3) render
    out = []
    out.append(f"# {data.get('project', 'UniTrade')} — NFR Evidence Report")
    out.append("")
    out.append("> Generated by the `NFR Evidence Report` CI job. **Do not edit by hand** — "
               "this document is stamped and hashed at generation time; hand edits break the hashes below.")
    out.append("")
    out.append("| | |")
    out.append("|---|---|")
    out.append(f"| Project | {data.get('project', 'UniTrade')} |")
    out.append(f"| SRS quality requirements | {data.get('srs_quality_requirements', '—')} |")
    out.append(f"| Commit | `{sha}` |")
    out.append(f"| Branch | `{ref}` |")
    out.append(f"| CI run (authoritative) | {run_url} |")
    out.append(f"| Generated | {now} |")
    out.append(f"| `traceability.yml` SHA-256 | `{matrix_hash}` |")
    out.append(f"| Summary | {tally} |")
    out.append("")
    out.append("## How to trust this document")
    out.append("")
    out.append("1. The **CI run** above is a record on GitHub's servers at a fixed commit — it cannot be "
               "rewritten after the fact, so it is the authoritative copy of this report.")
    out.append("2. Every evidence file is hashed in `tests/nfr/evidence/SHA256SUMS`. Re-verify at any time:")
    out.append("")
    out.append("   ```bash")
    out.append("   cd tests/nfr/evidence && sha256sum -c SHA256SUMS")
    out.append("   ```")
    out.append("3. Changing any evidence file (or the matrix) changes a hash, so it no longer matches "
               "the copy this run attached. Diverge from the run URL = tampered.")
    out.append("")
    out.append("## Quality requirements")

    # group by category, preserving first-seen order
    seen: list[str] = []
    by_cat: dict[str, list[dict]] = {}
    for r in reqs:
        cat = r.get("category", "Other")
        if cat not in by_cat:
            by_cat[cat] = []
            seen.append(cat)
        by_cat[cat].append(r)

    for cat in seen:
        out.append("")
        out.append(f"### {cat}")
        out.append("")
        out.append("| QR | Requirement | Target | Verification | Status | Evidence |")
        out.append("|----|-------------|--------|--------------|--------|----------|")
        for r in by_cat[cat]:
            out.append(
                f"| `{r.get('id','')}` "
                f"| {md_escape(r.get('requirement',''))} "
                f"| {md_escape(r.get('target',''))} "
                f"| {verification_cell(r)} "
                f"| {STATUS_LABEL.get(r.get('status',''), r.get('status',''))} "
                f"| {evidence_cell(r)} |"
            )

    out.append("")
    out.append("## SHA256SUMS (evidence tree)")
    out.append("")
    out.append("```")
    out.append("\n".join(sum_lines) if sum_lines else "(no evidence files committed yet)")
    out.append("```")
    out.append("")

    OUT_MD.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_MD} ({len(reqs)} requirements, {len(files)} evidence files hashed).")


if __name__ == "__main__":
    main()
