services:
   db:
    image: postgres:18
    container_name: Unitrade-DB
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER_ID}
      POSTGRES_DB: ${DB_NAME}

      APP_USER: ${APP_USER_ID}
      APP_USER_PASSWORD: ${APP_USER_PASSWORD}
    volumes:
    - db_data:/var/lib/postgresql
    - ../../database/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_ID} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    
   pgadmin:
    image: dpage/pgadmin4
    container_name: unitrade-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_ADMIN}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  
   backend:
    build:
      context: ../..
      dockerfile: src/backend/Api/Dockerfile
    container_name: unitrade-backend
    
    ports:
    - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=${DB_NAME};Username=${APP_USER_ID};Password=${APP_USER_PASSWORD}"
      ConnectionStrings__MigrationsConnection: "Host=db;Port=5432;Database=${DB_NAME};Username=${POSTGRES_USER_ID};Password=${POSTGRES_PASSWORD}"
      Jwt__Secret: ${Jwt__Secret}
      Otp__Secret: ${Otp__Secret}
      Acs__SenderAddress: ${Acs__SenderAddress}
      Acs__ConnectionString: ${Acs__ConnectionString}
    depends_on:
     db: 
       condition: service_healthy
   frontend:
    build:
      context: ../../src/web
      dockerfile: Dockerfile
    container_name: unitrade-web
    environment:
        VITE_API_URL: ${VITE_API_URL}
    ports:
    - "3000:3000"
    depends_on:
     - backend
        

volumes: 
  db_data:
  pgadmin_data:
