name: Backend CI

on:
  push:
    branches: ["**"]
    paths:
      - "src/backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches: ["dev","main"]
    paths:
      - "src/backend/**"
      - ".github/workflows/backend-ci.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore API
        run: dotnet restore src/backend/Api/Api.csproj
      
      - name: Restore Tests
        run: dotnet restore src/backend/Tests/UniTrade.Tests.csproj
        
      - name: Build API
        working-directory: src/backend/Api
        run: dotnet build --configuration Release --no-restore

      - name: Build Tests
        working-directory: src/backend/Tests
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        working-directory: src/backend/Tests
        run: dotnet test --configuration Release --no-build --logger "console;verbosity=normal" --filter "Category=Unit" 

      - name: Run Integration Tests
        working-directory: src/backend/Tests
        run: dotnet test --configuration Release --no-build --logger "console;verbosity=normal" --filter "Category=Integration" 
    

  code-quality:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore API
        run: dotnet restore src/backend/Api/Api.csproj


      - name: Analyze code style
        run: dotnet build src/backend/Api/Api.csproj --configuration Release --no-restore /p:EnforceCodeStyleInBuild=true
