name: UniTrade Pipeline
on:
    push:
        branches: ["main", "dev","feature/backend/refiningPayments"]
    workflow_dispatch:
permissions:
    id-token: write
    contents: read
concurrency:
    group: pipeline-${{ github.ref }}
    cancel-in-progress: false

jobs: 
    backend-ci:
        uses: ./.github/workflows/backend-ci.yml
        secrets: inherit
    web-ci:
        uses: ./.github/workflows/web-ci.yml
        secrets: inherit
    deploy:
        needs: [backend-ci, web-ci]
        uses: ./.github/workflows/cd.yml
        secrets: inherit