name: Web Frontend CI

on:
  push:
    branches: ["**"]
    paths:
      - "src/web/**"
      - ".github/workflows/web-ci.yml"
  pull_request:
    branches: ["dev","main"]
    paths:
      - "src/web/**"
      - ".github/workflows/web-ci.yml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: ["20.x"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "src/web/package-lock.json"

      - name: Install dependencies
        working-directory: src/web
        run: npm ci

      - name: Lint code
        working-directory: src/web
        run: npm run lint
      
      - name: Validate frontend env
        working-directory: src/web
        env: 
          VITE_API_URL: ${{secrets.VITE_API_URL}}
        run: |
         : "${VITE_API_URL:?VITE_API_URL is required for frontend build}"
        
      - name: Build application
        working-directory: src/web
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL}}
        run: npm run build

      - name: Run unit tests
        working-directory: src/web
        run: npm run test:run 

      - name: Validate Frontend docker image
        working-directory: src/web
        run: docker build -f src/web/Dockerfile -t unitrade-web-ci .
